server:
  port: 8762
spring:
  application:
    name: nativeconfigserver
  profiles:
    active: native
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edu?characterEncoding=utf-8&useSSL=false
    password: 123456
    username: root
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared